name: CI
on: [pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        
      - name: Setup Zig env
        uses: goto-bus-stop/setup-zig@v2
        with: 
            version: "master"

      - name: Check Zig version
        run: zig version

      - name: Install XTP CLI
        run: curl https://static.dylibso.com/cli/install.sh | sudo sh

      - name: Build example
        run: zig build

      - name: Test example
        run: xtp plugin test https://raw.githubusercontent.com/extism/extism/main/wasm/code.wasm --with zig-out/bin/basic-test.wasm
      
