name: CI
on: [pull_request, push, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        
      - name: Setup Zig env
        uses: goto-bus-stop/setup-zig@v2

      - name: Check Zig version
        run: zig version

      - name: Install XTP CLI
        run: curl https://static.dylibso.com/cli/install.sh | sudo sh

      - name: Build example
        run: zig build

      - name: Test example
        run: |
          # this is configured by the `xtp.toml` in the root
          xtp plugin test --path examples/basic
          xtp plugin test --path examples/json
      
